# Numpy

An introduction



<p align="left"><img src="https://user-images.githubusercontent.com/98330/64479472-4b35c900-d16c-11e9-8d49-71fc02cd539f.png" width="500", height="500"></p>


In [1]:
import numpy as np

In [6]:
# One dimensional array
arr_a= np.array([1, 2, 3, 4, 5])
print("This is a 1D array: ")
print(arr_a)  # [1 2 3 4 5]

# Two dimensional array
arr_b = np.array([[1, 2, 3], [4, 5, 6]])  
print("This is a 2D array: ")
print(arr_b)  # [[1 2 3]
            #  [4 5 6]]

# Three dimensional array
arr_c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])    
print("This is a 3D array: ")
print(arr_c)  # [[[ 1  2  3]
            #   [ 4  5  6]]
            #  [[ 7  8  9]
            #   [10 11 12]]]

# Check the number of dimensions
print("Number of dimensions of arr_a: ")
print(arr_a.ndim)  # 1
print("Number of dimensions of arr_b: ")
print(arr_b.ndim)  # 2
print("Number of dimensions of arr_c: ")
print(arr_c.ndim)  # 3

              


This is a 1D array: 
[1 2 3 4 5]
This is a 2D array: 
[[1 2 3]
 [4 5 6]]
This is a 3D array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions of arr_a: 
1
Number of dimensions of arr_b: 
2
Number of dimensions of arr_c: 
3


## Accessing elememts in an array

In [7]:
# Accessing elements of an array
# One dimensional array

print("Accessing elements of a 1D array: ")
print(arr_a[0])  # 1

# Two dimensional array
print("Accessing elements of a 2D array: ")
print("The second element of the first row is : ")
print(arr_b[0, 1])  # 2
print("The third element of the second row is : ")
print(arr_b[1, 2])  # 6

# Three dimensional array
print("Accessing elements of a 3D array: ")
print("The second element of the first row of the first matrix is : ")
print(arr_c[0, 0, 1])  # 2

#Explaining the above example:
#The first number represents the first dimension, which contains two arrays: [[1, 2, 3], [4, 5, 6]] and [[7, 8, 9], [10, 11, 12]].
#Since we selected 0, we are left with the following two arrays: [[1, 2, 3], [4, 5, 6]].
#The second number represents the second dimension, which also contains two arrays: [1, 2, 3] and [4, 5, 6].
#Since we selected 0, we are left with the first array: [1, 2, 3].
#The third number represents the third dimension, which contains three values: 1, 2, and 3.
#Since we selected 1, the final value is 2.


Accessing elements of a 1D array: 
1
Accessing elements of a 2D array: 
The second element of the first row is : 
2
The third element of the second row is : 
6
Accessing elements of a 3D array: 
The second element of the first row of the first matrix is : 
2


## Slicing arrays


In [ ]:
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].

# The result includes the start index, but excludes the end index.

# One dimensional array
print("Slicing elements of a 1D array: ")
print(arr_a[1:4])  # [2 3 4]

# Two dimensional array
print("Slicing elements of a 2D array: ")
print("The first row is : ")    
print(arr_b[0, 0:2])  # [1 2]
print("The second column is : ")
print(arr_b[0:2, 1])  # [2 5]