# Numpy Types 

---

In [1]:
import numpy as np

In [7]:
L = np.array([[1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]])

In [8]:
print(L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
L.dtype

dtype('int64')

In [10]:
L.mean()


5.0

In [13]:
np.arange(9).reshape(3,3) + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Get a specific element [r,c]

In [16]:
#Get a specific element [r, c]
a[1, 5]


13

Get a specific row

In [17]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

Get a specific column


In [18]:
#Get a specific column
a[:, 2]

array([ 3, 10])

Getting a little more fancy [startindex: endindes: stepsize]

In [19]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]


array([2, 4, 6])