# Numpy Types 

---

In [1]:
import numpy as np

In [7]:
L = np.array([[1, 2, 3],[ 4, 5, 6],[ 7, 8, 9]])

In [8]:
print(L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
L.dtype

dtype('int64')

In [10]:
L.mean()


5.0

In [13]:
np.arange(9).reshape(3,3) + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])